### ISSUE TITLE
multus IP address prefix alignment with sopnode connection management

### ISSUE THREAD

**Issue by vinod-git** [sopnode/kubernetes#6]
The multus IP address prefix needed to be aligned with prefixes provided by sopnode connection management (https://github.com/dsaucez/SLICES/blob/main/sopnode/connectivity.md) i.e. 192.168.100

**Comment by dsaucez** [comment]
not sure I understand the issue, what's the problem? IP addresses are automatically assigned in `p4-network` using Multus.

**Comment by vinod-git** [comment]
Though IP addresses are automatically assigned in p4-network, multus needs the IP address prefix and range to be provided through rangeStart and rangeEnd variable in yaml file. The reference for this range is the connectivity setup provided in https://github.com/dsaucez/SLICES/blob/main/sopnode/connectivity.md.

**Comment by parmentelat** [comment]
it feels like taking the creation of network attachments out of this module has made this issue irrelevant
closing for now, feel free to re-open if needed
