### ISSUE TITLE
rollback recent changes

### ISSUE THREAD

**Issue by parmentelat** [sopnode/kubernetes#7]
I need to define a clean way to rollback the changes that have been added onto the main branch
i.e. 362c1ee, fa9c5e4, and abf73c9

### discussion 1
as far as I am concerned, none if these changes is needed, and some are actually breaking the tests

so I propose that we 
1. either rollback the 3 commits entirely
1. or keep them in a specific branch (`vinod` comes to mind)

I would be in favor of 1. personnally, but have nothing against 2. if these changes are deemed valuable by others

### discussion 2
regardless of 1., I need to be sure that everybody will rollback the `main` branch in their local repos too, because otherwise these changes will make it back here, just later down the road

### digression
among the changes in there, there is one about improving the `switch-branch` function, which is something I will address in a separate issue

**Comment by vinod-git** [comment]
Comment on discussion 1:
The changes 362c1ee, fa9c5e4, and abf73c9 are now realized using appropriate usage of a separate yaml file. So I would also prefer Option 1.

**Comment by parmentelat** [comment]
deemed OK now
